//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Не указан главный комментарий ветки ähnelt.
        /// </summary>
        internal static string AddCommentHeadCommentRequired {
            get {
                return ResourceManager.GetString("AddCommentHeadCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Не указан родительский комментарий ähnelt.
        /// </summary>
        internal static string AddCommentParentCommentRequired {
            get {
                return ResourceManager.GetString("AddCommentParentCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарий должен быть не длиннее 4000 символов ähnelt.
        /// </summary>
        internal static string AddCommentTextLength {
            get {
                return ResourceManager.GetString("AddCommentTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите текст комментария ähnelt.
        /// </summary>
        internal static string AddCommentTextRequired {
            get {
                return ResourceManager.GetString("AddCommentTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Повторный ввод не совпадает с первым ähnelt.
        /// </summary>
        internal static string ChangePasswordConfirmNewPasswordCompare {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmNewPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите пароль ähnelt.
        /// </summary>
        internal static string ChangePasswordConfirmNewPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите пароль ähnelt.
        /// </summary>
        internal static string ChangePasswordNewPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите пароль ähnelt.
        /// </summary>
        internal static string ChangePasswordOldPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль должен быть не короче 3 и не длиннее 32 символов ähnelt.
        /// </summary>
        internal static string ChangePasswordPasswordLength {
            get {
                return ResourceManager.GetString("ChangePasswordPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Хештег должен быть не длиннее 100 символов ähnelt.
        /// </summary>
        internal static string EditBookHashTagLength {
            get {
                return ResourceManager.GetString("EditBookHashTagLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Введен некорректный e-mail ähnelt.
        /// </summary>
        internal static string EditProfileEmailDataType {
            get {
                return ResourceManager.GetString("EditProfileEmailDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите e-mail ähnelt.
        /// </summary>
        internal static string EditProfileEmailRequired {
            get {
                return ResourceManager.GetString("EditProfileEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Имя пользователя должно быть не короче 3 и не длиннее 150 символов ähnelt.
        /// </summary>
        internal static string EditProfileNameLength {
            get {
                return ResourceManager.GetString("EditProfileNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите имя пользователя ähnelt.
        /// </summary>
        internal static string EditProfileNameRequired {
            get {
                return ResourceManager.GetString("EditProfileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Разрешены только следующие символы: a-z0-9_. ähnelt.
        /// </summary>
        internal static string EditSettingsUrlNameAllowedCharacters {
            get {
                return ResourceManager.GetString("EditSettingsUrlNameAllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Имя пользователя для Url должно быть не короче 3 и не длиннее 150 символов ähnelt.
        /// </summary>
        internal static string EditSettingsUrlNameLength {
            get {
                return ResourceManager.GetString("EditSettingsUrlNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Введен некорректный e-mail ähnelt.
        /// </summary>
        internal static string LoginEmailDataType {
            get {
                return ResourceManager.GetString("LoginEmailDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите e-mail ähnelt.
        /// </summary>
        internal static string LoginEmailRequired {
            get {
                return ResourceManager.GetString("LoginEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль должен быть не короче 3 и не длиннее 32 символов ähnelt.
        /// </summary>
        internal static string LoginPasswordLength {
            get {
                return ResourceManager.GetString("LoginPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите пароль ähnelt.
        /// </summary>
        internal static string LoginPasswordRequired {
            get {
                return ResourceManager.GetString("LoginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Введен некорректный e-mail ähnelt.
        /// </summary>
        internal static string RegisterEmailDataType {
            get {
                return ResourceManager.GetString("RegisterEmailDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите e-mail ähnelt.
        /// </summary>
        internal static string RegisterEmailRequired {
            get {
                return ResourceManager.GetString("RegisterEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Имя пользователя должно быть не короче 3 и не длиннее 150 символов ähnelt.
        /// </summary>
        internal static string RegisterNameLength {
            get {
                return ResourceManager.GetString("RegisterNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите имя пользователя ähnelt.
        /// </summary>
        internal static string RegisterNameRequired {
            get {
                return ResourceManager.GetString("RegisterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль должен быть не короче 3 и не длиннее 32 символов ähnelt.
        /// </summary>
        internal static string RegisterPasswordLength {
            get {
                return ResourceManager.GetString("RegisterPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, введите пароль ähnelt.
        /// </summary>
        internal static string RegisterPasswordRequired {
            get {
                return ResourceManager.GetString("RegisterPasswordRequired", resourceCulture);
            }
        }
    }
}
