//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Book {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Book() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.Book", typeof(Book).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Большое Вам Спасибо! ähnelt.
        /// </summary>
        public static string AcceptDonationHeading {
            get {
                return ResourceManager.GetString("AcceptDonationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Большое Вам Спасибо! ähnelt.
        /// </summary>
        public static string AcceptDonationTitle {
            get {
                return ResourceManager.GetString("AcceptDonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить закладку ähnelt.
        /// </summary>
        public static string AddBookmarkHeading {
            get {
                return ResourceManager.GetString("AddBookmarkHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить закладку ähnelt.
        /// </summary>
        public static string AddBookmarkSubmitButtonText {
            get {
                return ResourceManager.GetString("AddBookmarkSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Название закладки ähnelt.
        /// </summary>
        public static string AddBookmarkTitleFieldName {
            get {
                return ResourceManager.GetString("AddBookmarkTitleFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет комментариев ähnelt.
        /// </summary>
        public static string AllCommentsNoCommentsMessage {
            get {
                return ResourceManager.GetString("AllCommentsNoCommentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die открыть ветку ähnelt.
        /// </summary>
        public static string AllCommentsOpenBranchLinkText {
            get {
                return ResourceManager.GetString("AllCommentsOpenBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии к ähnelt.
        /// </summary>
        public static string AllCommentsTitle {
            get {
                return ResourceManager.GetString("AllCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die к тексту ähnelt.
        /// </summary>
        public static string AllCommentsToTextLinkText {
            get {
                return ResourceManager.GetString("AllCommentsToTextLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книгу комментируют ähnelt.
        /// </summary>
        public static string AnnotationCommentatorsHeading {
            get {
                return ResourceManager.GetString("AnnotationCommentatorsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die всего ähnelt.
        /// </summary>
        public static string AnnotationCommentCountMessage {
            get {
                return ResourceManager.GetString("AnnotationCommentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die КОММЕНТАРИИ ähnelt.
        /// </summary>
        public static string AnnotationCommentsLinkText {
            get {
                return ResourceManager.GetString("AnnotationCommentsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die скрыть ähnelt.
        /// </summary>
        public static string AnnotationHideAllLinkText {
            get {
                return ResourceManager.GetString("AnnotationHideAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ЧИТАТЬ ähnelt.
        /// </summary>
        public static string AnnotationReadLinkText {
            get {
                return ResourceManager.GetString("AnnotationReadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die всего ähnelt.
        /// </summary>
        public static string AnnotationRecentCommentCountMessage {
            get {
                return ResourceManager.GetString("AnnotationRecentCommentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Свежие комментарии ähnelt.
        /// </summary>
        public static string AnnotationRecentCommentsHeading {
            get {
                return ResourceManager.GetString("AnnotationRecentCommentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет аннотации ähnelt.
        /// </summary>
        public static string AnnotationShortNoAnnotationMessage {
            get {
                return ResourceManager.GetString("AnnotationShortNoAnnotationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die вся аннотация ähnelt.
        /// </summary>
        public static string AnnotationShowAllLinkText {
            get {
                return ResourceManager.GetString("AnnotationShowAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die еще к этой книге ähnelt.
        /// </summary>
        public static string BestCommentMoreToThisBookMessage {
            get {
                return ResourceManager.GetString("BestCommentMoreToThisBookMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die удалить ähnelt.
        /// </summary>
        public static string BookmarksDeleteButtonText {
            get {
                return ResourceManager.GetString("BookmarksDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет закладок ähnelt.
        /// </summary>
        public static string BookmarksNoBookmarksMessage {
            get {
                return ResourceManager.GetString("BookmarksNoBookmarksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга потерялась ähnelt.
        /// </summary>
        public static string NotFoundHeading {
            get {
                return ResourceManager.GetString("NotFoundHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Почитайте что-нибудь другое. ähnelt.
        /// </summary>
        public static string NotFoundReadSomethingElseMessage {
            get {
                return ResourceManager.GetString("NotFoundReadSomethingElseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга потерялась ähnelt.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die В библиотеку ähnelt.
        /// </summary>
        public static string NotFoundToLibraryLinkText {
            get {
                return ResourceManager.GetString("NotFoundToLibraryLinkText", resourceCulture);
            }
        }
    }
}
