//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Book {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Book() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.Book", typeof(Book).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Большое Вам Спасибо! ähnelt.
        /// </summary>
        public static string AcceptDonationHeading {
            get {
                return ResourceManager.GetString("AcceptDonationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Большое Вам Спасибо! ähnelt.
        /// </summary>
        public static string AcceptDonationTitle {
            get {
                return ResourceManager.GetString("AcceptDonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить закладку ähnelt.
        /// </summary>
        public static string AddBookmarkHeading {
            get {
                return ResourceManager.GetString("AddBookmarkHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить закладку ähnelt.
        /// </summary>
        public static string AddBookmarkSubmitButtonText {
            get {
                return ResourceManager.GetString("AddBookmarkSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Название закладки ähnelt.
        /// </summary>
        public static string AddBookmarkTitleFieldName {
            get {
                return ResourceManager.GetString("AddBookmarkTitleFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет комментариев ähnelt.
        /// </summary>
        public static string AllCommentsNoCommentsMessage {
            get {
                return ResourceManager.GetString("AllCommentsNoCommentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die открыть ветку ähnelt.
        /// </summary>
        public static string AllCommentsOpenBranchLinkText {
            get {
                return ResourceManager.GetString("AllCommentsOpenBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии к ähnelt.
        /// </summary>
        public static string AllCommentsTitle {
            get {
                return ResourceManager.GetString("AllCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die к тексту ähnelt.
        /// </summary>
        public static string AllCommentsToTextLinkText {
            get {
                return ResourceManager.GetString("AllCommentsToTextLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книгу комментируют ähnelt.
        /// </summary>
        public static string AnnotationCommentatorsHeading {
            get {
                return ResourceManager.GetString("AnnotationCommentatorsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die всего ähnelt.
        /// </summary>
        public static string AnnotationCommentCountMessage {
            get {
                return ResourceManager.GetString("AnnotationCommentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die КОММЕНТАРИИ ähnelt.
        /// </summary>
        public static string AnnotationCommentsLinkText {
            get {
                return ResourceManager.GetString("AnnotationCommentsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die скрыть ähnelt.
        /// </summary>
        public static string AnnotationHideAllLinkText {
            get {
                return ResourceManager.GetString("AnnotationHideAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ЧИТАТЬ ähnelt.
        /// </summary>
        public static string AnnotationReadLinkText {
            get {
                return ResourceManager.GetString("AnnotationReadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die всего ähnelt.
        /// </summary>
        public static string AnnotationRecentCommentCountMessage {
            get {
                return ResourceManager.GetString("AnnotationRecentCommentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Свежие комментарии ähnelt.
        /// </summary>
        public static string AnnotationRecentCommentsHeading {
            get {
                return ResourceManager.GetString("AnnotationRecentCommentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет аннотации ähnelt.
        /// </summary>
        public static string AnnotationShortNoAnnotationMessage {
            get {
                return ResourceManager.GetString("AnnotationShortNoAnnotationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die вся аннотация ähnelt.
        /// </summary>
        public static string AnnotationShowAllLinkText {
            get {
                return ResourceManager.GetString("AnnotationShowAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die еще к этой книге ähnelt.
        /// </summary>
        public static string BestCommentMoreToThisBookMessage {
            get {
                return ResourceManager.GetString("BestCommentMoreToThisBookMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die удалить ähnelt.
        /// </summary>
        public static string BookmarksDeleteButtonText {
            get {
                return ResourceManager.GetString("BookmarksDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет закладок ähnelt.
        /// </summary>
        public static string BookmarksNoBookmarksMessage {
            get {
                return ResourceManager.GetString("BookmarksNoBookmarksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Знаменитости ähnelt.
        /// </summary>
        public static string CommentatorsCelebritiesHeading {
            get {
                return ResourceManager.GetString("CommentatorsCelebritiesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Друзья ähnelt.
        /// </summary>
        public static string CommentatorsFriendsHeading {
            get {
                return ResourceManager.GetString("CommentatorsFriendsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string CommentatorsPageAnnotationLinkText {
            get {
                return ResourceManager.GetString("CommentatorsPageAnnotationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Знаменитости ähnelt.
        /// </summary>
        public static string CommentatorsPageCelebritiesHeading {
            get {
                return ResourceManager.GetString("CommentatorsPageCelebritiesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Друзья ähnelt.
        /// </summary>
        public static string CommentatorsPageFriendsHeading {
            get {
                return ResourceManager.GetString("CommentatorsPageFriendsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нажмите на аватар, чтобы прочитать все комментарии пользователя ähnelt.
        /// </summary>
        public static string CommentatorsPageReadAllFromUserMessage {
            get {
                return ResourceManager.GetString("CommentatorsPageReadAllFromUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ЧИТАТЬ ähnelt.
        /// </summary>
        public static string CommentatorsPageReadLinkText {
            get {
                return ResourceManager.GetString("CommentatorsPageReadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Остальные ähnelt.
        /// </summary>
        public static string CommentatorsPageRestHeading {
            get {
                return ResourceManager.GetString("CommentatorsPageRestHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нажмите на аватар, чтобы прочитать все комментарии пользователя ähnelt.
        /// </summary>
        public static string CommentatorsReadAllFromUserMessage {
            get {
                return ResourceManager.GetString("CommentatorsReadAllFromUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Остальные ähnelt.
        /// </summary>
        public static string CommentatorsRestHeading {
            get {
                return ResourceManager.GetString("CommentatorsRestHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментировать абзац ähnelt.
        /// </summary>
        public static string CommentParagraphHeading {
            get {
                return ResourceManager.GetString("CommentParagraphHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментировать абзац ähnelt.
        /// </summary>
        public static string CommentParagraphTitle {
            get {
                return ResourceManager.GetString("CommentParagraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string CommentsByUserHeading {
            get {
                return ResourceManager.GetString("CommentsByUserHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет комментариев ähnelt.
        /// </summary>
        public static string CommentsByUserNoCommentsMessage {
            get {
                return ResourceManager.GetString("CommentsByUserNoCommentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die открыть ветку ähnelt.
        /// </summary>
        public static string CommentsByUserOpenBranchLinkText {
            get {
                return ResourceManager.GetString("CommentsByUserOpenBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читать книгу с этого места ähnelt.
        /// </summary>
        public static string CommentsByUserReadFromHereLinkText {
            get {
                return ResourceManager.GetString("CommentsByUserReadFromHereLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string CommentsByUserTitle {
            get {
                return ResourceManager.GetString("CommentsByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читать книгу с этого места ähnelt.
        /// </summary>
        public static string CommentsThreadReadFromHereLinkText {
            get {
                return ResourceManager.GetString("CommentsThreadReadFromHereLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string CommentsThreadTitle {
            get {
                return ResourceManager.GetString("CommentsThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string CommentsTitle {
            get {
                return ResourceManager.GetString("CommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Назад ähnelt.
        /// </summary>
        public static string CommentsToStartLinkText {
            get {
                return ResourceManager.GetString("CommentsToStartLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Автор книги не принимает пожертвования ähnelt.
        /// </summary>
        public static string ControllerAuthorDoesNotAcceptDonations {
            get {
                return ResourceManager.GetString("ControllerAuthorDoesNotAcceptDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Закладка ähnelt.
        /// </summary>
        public static string ControllerBookmark {
            get {
                return ResourceManager.GetString("ControllerBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Закладка не найдена ähnelt.
        /// </summary>
        public static string ControllerBookMarkNotFound {
            get {
                return ResourceManager.GetString("ControllerBookMarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die этот абзац нельзя комментировать ähnelt.
        /// </summary>
        public static string ControllerCantCommentParagraph {
            get {
                return ResourceManager.GetString("ControllerCantCommentParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Можно удалять только свои закладки ähnelt.
        /// </summary>
        public static string ControllerCantDeleteBookMark {
            get {
                return ResourceManager.GetString("ControllerCantDeleteBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Этот комментарий не относится к абзацу ähnelt.
        /// </summary>
        public static string ControllerCommentDoesNotBelongToParagraph {
            get {
                return ResourceManager.GetString("ControllerCommentDoesNotBelongToParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die комментарий не найден ähnelt.
        /// </summary>
        public static string ControllerCommentNotFound {
            get {
                return ResourceManager.GetString("ControllerCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die такой тип фильтра не поддерживается ähnelt.
        /// </summary>
        public static string ControllerFilterTypeNotSupported {
            get {
                return ResourceManager.GetString("ControllerFilterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нужно залогиниться ähnelt.
        /// </summary>
        public static string ControllerMustLogin {
            get {
                return ResourceManager.GetString("ControllerMustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Абзац не найден ähnelt.
        /// </summary>
        public static string ControllerParagraphNotFound {
            get {
                return ResourceManager.GetString("ControllerParagraphNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пользователь не найден ähnelt.
        /// </summary>
        public static string ControllerUserNotFound {
            get {
                return ResourceManager.GetString("ControllerUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die к книге ähnelt.
        /// </summary>
        public static string HeaderCommentsCountMessage {
            get {
                return ResourceManager.GetString("HeaderCommentsCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожертвовать ähnelt.
        /// </summary>
        public static string HeaderDonateLinkText {
            get {
                return ResourceManager.GetString("HeaderDonateLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string IndexAnnotationLinkText {
            get {
                return ResourceManager.GetString("IndexAnnotationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги ähnelt.
        /// </summary>
        public static string IndexHeading {
            get {
                return ResourceManager.GetString("IndexHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет ни одной книги ähnelt.
        /// </summary>
        public static string IndexNoBooksMessage {
            get {
                return ResourceManager.GetString("IndexNoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги ähnelt.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string LeftFrameAnnotationHeading {
            get {
                return ResourceManager.GetString("LeftFrameAnnotationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string LeftFrameAnnotationLinkText {
            get {
                return ResourceManager.GetString("LeftFrameAnnotationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Закладки ähnelt.
        /// </summary>
        public static string LeftFrameBookmarksHeading {
            get {
                return ResourceManager.GetString("LeftFrameBookmarksHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Закладки ähnelt.
        /// </summary>
        public static string LeftFrameBookmarksLinkText {
            get {
                return ResourceManager.GetString("LeftFrameBookmarksLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Оглавление ähnelt.
        /// </summary>
        public static string LeftFrameContentHeading {
            get {
                return ResourceManager.GetString("LeftFrameContentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Оглавление ähnelt.
        /// </summary>
        public static string LeftFrameContentLinkText {
            get {
                return ResourceManager.GetString("LeftFrameContentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string NavigationAnnotationLinkText {
            get {
                return ResourceManager.GetString("NavigationAnnotationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Назад ähnelt.
        /// </summary>
        public static string NavigationBackwardsLinkText {
            get {
                return ResourceManager.GetString("NavigationBackwardsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Начало ähnelt.
        /// </summary>
        public static string NavigationBeginningLinkText {
            get {
                return ResourceManager.GetString("NavigationBeginningLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string NavigationCommentsLinkText {
            get {
                return ResourceManager.GetString("NavigationCommentsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Дальше ähnelt.
        /// </summary>
        public static string NavigationForwardsLinkText {
            get {
                return ResourceManager.GetString("NavigationForwardsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга потерялась ähnelt.
        /// </summary>
        public static string NotFoundHeading {
            get {
                return ResourceManager.GetString("NotFoundHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Почитайте что-нибудь другое. ähnelt.
        /// </summary>
        public static string NotFoundReadSomethingElseMessage {
            get {
                return ResourceManager.GetString("NotFoundReadSomethingElseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга потерялась ähnelt.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die В библиотеку ähnelt.
        /// </summary>
        public static string NotFoundToLibraryLinkText {
            get {
                return ResourceManager.GetString("NotFoundToLibraryLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die комментировать ähnelt.
        /// </summary>
        public static string ParagraphContainerCommentLinkTip {
            get {
                return ResourceManager.GetString("ParagraphContainerCommentLinkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die скрыть ähnelt.
        /// </summary>
        public static string ParagraphContainerHideButtonText {
            get {
                return ResourceManager.GetString("ParagraphContainerHideButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string ProfileAnnotationLinkText {
            get {
                return ResourceManager.GetString("ProfileAnnotationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ЧИТАТЬ ähnelt.
        /// </summary>
        public static string ProfileReadLinkText {
            get {
                return ResourceManager.GetString("ProfileReadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментарии ähnelt.
        /// </summary>
        public static string RightFrameCommentsHeading {
            get {
                return ResourceManager.GetString("RightFrameCommentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Начало ähnelt.
        /// </summary>
        public static string RootChapterBeginningLinkText {
            get {
                return ResourceManager.GetString("RootChapterBeginningLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die подписаться ähnelt.
        /// </summary>
        public static string SelectedCommentatorsSubscribeButtonText {
            get {
                return ResourceManager.GetString("SelectedCommentatorsSubscribeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die отписаться ähnelt.
        /// </summary>
        public static string SelectedCommentatorsUnsubscribeButtonText {
            get {
                return ResourceManager.GetString("SelectedCommentatorsUnsubscribeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Далее ähnelt.
        /// </summary>
        public static string ViewNavigateDownButtonText {
            get {
                return ResourceManager.GetString("ViewNavigateDownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Назад ähnelt.
        /// </summary>
        public static string ViewNavigateUpButtonText {
            get {
                return ResourceManager.GetString("ViewNavigateUpButtonText", resourceCulture);
            }
        }
    }
}
