//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookAdmin() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.BookAdmin", typeof(BookAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга не найдена ähnelt.
        /// </summary>
        public static string ControllerBookNotFoundException {
            get {
                return ResourceManager.GetString("ControllerBookNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Глава имеет вложенные главы. Нельзя удалить. ähnelt.
        /// </summary>
        public static string ControllerCantDeleteChapter {
            get {
                return ResourceManager.GetString("ControllerCantDeleteChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Абзац имеет комментарии. Нельзя удалить. ähnelt.
        /// </summary>
        public static string ControllerCantDeleteParagraph {
            get {
                return ResourceManager.GetString("ControllerCantDeleteParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Глава успешно удалена ähnelt.
        /// </summary>
        public static string ControllerChapterDeleted {
            get {
                return ResourceManager.GetString("ControllerChapterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Глава не найдена ähnelt.
        /// </summary>
        public static string ControllerChapterNotFound {
            get {
                return ResourceManager.GetString("ControllerChapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Неверный формат данных ähnelt.
        /// </summary>
        public static string ControllerInvalidDataFormat {
            get {
                return ResourceManager.GetString("ControllerInvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет прав на добавление книг. ähnelt.
        /// </summary>
        public static string ControllerNoPermissionToAddBooks {
            get {
                return ResourceManager.GetString("ControllerNoPermissionToAddBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет прав на удаление книг. ähnelt.
        /// </summary>
        public static string ControllerNoPermissionToDeleteBooks {
            get {
                return ResourceManager.GetString("ControllerNoPermissionToDeleteBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет прав на редактирование книги. ähnelt.
        /// </summary>
        public static string ControllerNoPermissionToEditBook {
            get {
                return ResourceManager.GetString("ControllerNoPermissionToEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет прав на редактирование книг. ähnelt.
        /// </summary>
        public static string ControllerNoPermissionToEditBooks {
            get {
                return ResourceManager.GetString("ControllerNoPermissionToEditBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Абзац успешно удален ähnelt.
        /// </summary>
        public static string ControllerParagraphDeleted {
            get {
                return ResourceManager.GetString("ControllerParagraphDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Абзац не найден ähnelt.
        /// </summary>
        public static string ControllerParagraphNotFound {
            get {
                return ResourceManager.GetString("ControllerParagraphNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить главу ähnelt.
        /// </summary>
        public static string DeleteChapterHeading {
            get {
                return ResourceManager.GetString("DeleteChapterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить ähnelt.
        /// </summary>
        public static string DeleteChapterSubmitButtonText {
            get {
                return ResourceManager.GetString("DeleteChapterSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить главу ähnelt.
        /// </summary>
        public static string DeleteChapterTitle {
            get {
                return ResourceManager.GetString("DeleteChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить абзац ähnelt.
        /// </summary>
        public static string DeleteParagraphHeading {
            get {
                return ResourceManager.GetString("DeleteParagraphHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить ähnelt.
        /// </summary>
        public static string DeleteParagraphSubmitButtonText {
            get {
                return ResourceManager.GetString("DeleteParagraphSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить абзац ähnelt.
        /// </summary>
        public static string DeleteParagraphTitle {
            get {
                return ResourceManager.GetString("DeleteParagraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Разделы каталога ähnelt.
        /// </summary>
        public static string EditBookCatalogFoldersHeading {
            get {
                return ResourceManager.GetString("EditBookCatalogFoldersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Выбрать аватар ähnelt.
        /// </summary>
        public static string EditBookChooseAvatarHeading {
            get {
                return ResourceManager.GetString("EditBookChooseAvatarHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Загрузить ähnelt.
        /// </summary>
        public static string EditBookChooseAvatarSubmitButtonText {
            get {
                return ResourceManager.GetString("EditBookChooseAvatarSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Аннотация ähnelt.
        /// </summary>
        public static string EditBookFieldLabelAnnotation {
            get {
                return ResourceManager.GetString("EditBookFieldLabelAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail автора ähnelt.
        /// </summary>
        public static string EditBookFieldLabelAuthorEmail {
            get {
                return ResourceManager.GetString("EditBookFieldLabelAuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Внутренние стили ähnelt.
        /// </summary>
        public static string EditBookFieldLabelCustomStyles {
            get {
                return ResourceManager.GetString("EditBookFieldLabelCustomStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meta description ähnelt.
        /// </summary>
        public static string EditBookFieldLabelDescription {
            get {
                return ResourceManager.GetString("EditBookFieldLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Форма для пожертвования ähnelt.
        /// </summary>
        public static string EditBookFieldLabelDonationForm {
            get {
                return ResourceManager.GetString("EditBookFieldLabelDonationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сообщение жертвователю ähnelt.
        /// </summary>
        public static string EditBookFieldLabelDonationMessage {
            get {
                return ResourceManager.GetString("EditBookFieldLabelDonationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Хэштег ähnelt.
        /// </summary>
        public static string EditBookFieldLabelHashTag {
            get {
                return ResourceManager.GetString("EditBookFieldLabelHashTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meta keywords ähnelt.
        /// </summary>
        public static string EditBookFieldLabelKeywords {
            get {
                return ResourceManager.GetString("EditBookFieldLabelKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Тип собственности ähnelt.
        /// </summary>
        public static string EditBookFieldLabelPropertyStatus {
            get {
                return ResourceManager.GetString("EditBookFieldLabelPropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Редактирование книги ähnelt.
        /// </summary>
        public static string EditBookHeading {
            get {
                return ResourceManager.GetString("EditBookHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die С пожертвованиями ähnelt.
        /// </summary>
        public static string EditBookPropertyStatusOptionDonatable {
            get {
                return ResourceManager.GetString("EditBookPropertyStatusOptionDonatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Платная ähnelt.
        /// </summary>
        public static string EditBookPropertyStatusOptionPrivate {
            get {
                return ResourceManager.GetString("EditBookPropertyStatusOptionPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Бесплатная ähnelt.
        /// </summary>
        public static string EditBookPropertyStatusOptionPublic {
            get {
                return ResourceManager.GetString("EditBookPropertyStatusOptionPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string EditBookSubmitButtonText {
            get {
                return ResourceManager.GetString("EditBookSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Редактирование книги ähnelt.
        /// </summary>
        public static string EditBookTitle {
            get {
                return ResourceManager.GetString("EditBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Назад ähnelt.
        /// </summary>
        public static string EditBookToIndexLinkText {
            get {
                return ResourceManager.GetString("EditBookToIndexLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die удалить ähnelt.
        /// </summary>
        public static string IndexDeleteButtonText {
            get {
                return ResourceManager.GetString("IndexDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги (управление) ähnelt.
        /// </summary>
        public static string IndexHeading {
            get {
                return ResourceManager.GetString("IndexHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет ни одной книги ähnelt.
        /// </summary>
        public static string IndexNoBooksMessage {
            get {
                return ResourceManager.GetString("IndexNoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string IndexSaveButtonText {
            get {
                return ResourceManager.GetString("IndexSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги (управление) ähnelt.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
    }
}
