//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalog() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.Catalog", typeof(Catalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книга не найдена ähnelt.
        /// </summary>
        public static string ControllerBookNotFound {
            get {
                return ResourceManager.GetString("ControllerBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Вы не можете редактировать каталог ähnelt.
        /// </summary>
        public static string ControllerCantEditCatalog {
            get {
                return ResourceManager.GetString("ControllerCantEditCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Такая категория уже существует ähnelt.
        /// </summary>
        public static string ControllerCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("ControllerCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Категория не найдена ähnelt.
        /// </summary>
        public static string ControllerCategoryNotFound {
            get {
                return ResourceManager.GetString("ControllerCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Категория не найдена (возможно, уже удалена) ähnelt.
        /// </summary>
        public static string ControllerCategoryNotFoundMaybeDeleted {
            get {
                return ResourceManager.GetString("ControllerCategoryNotFoundMaybeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Родительская категория не найдена (возможно, удалена) ähnelt.
        /// </summary>
        public static string ControllerParentCategoryNotFound {
            get {
                return ResourceManager.GetString("ControllerParentCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Лучшие комментарии ähnelt.
        /// </summary>
        public static string IndexBestCommentsHeading {
            get {
                return ResourceManager.GetString("IndexBestCommentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги ähnelt.
        /// </summary>
        public static string IndexHeading {
            get {
                return ResourceManager.GetString("IndexHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Каталог ähnelt.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить категорию ähnelt.
        /// </summary>
        public static string ManageAddCategoryHeading {
            get {
                return ResourceManager.GetString("ManageAddCategoryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить ähnelt.
        /// </summary>
        public static string ManageAddCategorySubmitButtonText {
            get {
                return ResourceManager.GetString("ManageAddCategorySubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить ähnelt.
        /// </summary>
        public static string ManageBookCategoriesAddButtonText {
            get {
                return ResourceManager.GetString("ManageBookCategoriesAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить категорию ähnelt.
        /// </summary>
        public static string ManageBookCategoriesAddCategoryHeading {
            get {
                return ResourceManager.GetString("ManageBookCategoriesAddCategoryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Категория ähnelt.
        /// </summary>
        public static string ManageBookCategoriesCategoryNameFieldName {
            get {
                return ResourceManager.GetString("ManageBookCategoriesCategoryNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить ähnelt.
        /// </summary>
        public static string ManageBookCategoriesDeleteButtonText {
            get {
                return ResourceManager.GetString("ManageBookCategoriesDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги в категории ähnelt.
        /// </summary>
        public static string ManageCategoryContentBooksInCategoryHeading {
            get {
                return ResourceManager.GetString("ManageCategoryContentBooksInCategoryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги во вложенных категориях ähnelt.
        /// </summary>
        public static string ManageCategoryContentBooksInChildCategoriesHeading {
            get {
                return ResourceManager.GetString("ManageCategoryContentBooksInChildCategoriesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die удалить ähnelt.
        /// </summary>
        public static string ManageCategoryContentDeleteButtonText {
            get {
                return ResourceManager.GetString("ManageCategoryContentDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги в категории ähnelt.
        /// </summary>
        public static string ManageCategoryContentHeading {
            get {
                return ResourceManager.GetString("ManageCategoryContentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нет ни одной книжки ähnelt.
        /// </summary>
        public static string ManageCategoryContentNoBooksMessage {
            get {
                return ResourceManager.GetString("ManageCategoryContentNoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги в категории ähnelt.
        /// </summary>
        public static string ManageCategoryContentTitle {
            get {
                return ResourceManager.GetString("ManageCategoryContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Удалить ähnelt.
        /// </summary>
        public static string ManageCategoryDeleteButtonText {
            get {
                return ResourceManager.GetString("ManageCategoryDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ред. ähnelt.
        /// </summary>
        public static string ManageCategoryEditButtonText {
            get {
                return ResourceManager.GetString("ManageCategoryEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Название ähnelt.
        /// </summary>
        public static string ManageCategoryNameFieldName {
            get {
                return ResourceManager.GetString("ManageCategoryNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Редактировать категорию ähnelt.
        /// </summary>
        public static string ManageEditCategoryHeading {
            get {
                return ResourceManager.GetString("ManageEditCategoryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string ManageEditCategorySubmitButtonText {
            get {
                return ResourceManager.GetString("ManageEditCategorySubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Каталог - управление ähnelt.
        /// </summary>
        public static string ManageHeading {
            get {
                return ResourceManager.GetString("ManageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Родительская ähnelt.
        /// </summary>
        public static string ManageParentCategoryFieldName {
            get {
                return ResourceManager.GetString("ManageParentCategoryFieldName", resourceCulture);
            }
        }
    }
}
