//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ответить ähnelt.
        /// </summary>
        public static string AddCommentBoxHeading {
            get {
                return ResourceManager.GetString("AddCommentBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string AddCommentBoxSaveButtonText {
            get {
                return ResourceManager.GetString("AddCommentBoxSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Оставить приватным ähnelt.
        /// </summary>
        public static string AddHeadCommentBoxAsPrivateFieldName {
            get {
                return ResourceManager.GetString("AddHeadCommentBoxAsPrivateFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить комментарий ähnelt.
        /// </summary>
        public static string AddHeadCommentBoxHeading {
            get {
                return ResourceManager.GetString("AddHeadCommentBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Укажите свой профиль ähnelt.
        /// </summary>
        public static string AddHeadCommentBoxProfileFieldName {
            get {
                return ResourceManager.GetString("AddHeadCommentBoxProfileFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сказать! ähnelt.
        /// </summary>
        public static string AddHeadCommentBoxProfileFieldNameSayButtonText {
            get {
                return ResourceManager.GetString("AddHeadCommentBoxProfileFieldNameSayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Поделиться цитатой ähnelt.
        /// </summary>
        public static string AddHeadCommentBoxShareMessage {
            get {
                return ResourceManager.GetString("AddHeadCommentBoxShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die друзья ähnelt.
        /// </summary>
        public static string CommentatorsDropdownFriendsOption {
            get {
                return ResourceManager.GetString("CommentatorsDropdownFriendsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die никого ähnelt.
        /// </summary>
        public static string CommentatorsDropdownPrivateOption {
            get {
                return ResourceManager.GetString("CommentatorsDropdownPrivateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die все ähnelt.
        /// </summary>
        public static string CommentatorsDropdownPublicOption {
            get {
                return ResourceManager.GetString("CommentatorsDropdownPublicOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Комментаторы ähnelt.
        /// </summary>
        public static string CommentatorsPopupHeading {
            get {
                return ResourceManager.GetString("CommentatorsPopupHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Все ähnelt.
        /// </summary>
        public static string CommentFilterAllOption {
            get {
                return ResourceManager.GetString("CommentFilterAllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Звезды ähnelt.
        /// </summary>
        public static string CommentFilterCelebsOption {
            get {
                return ResourceManager.GetString("CommentFilterCelebsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Друзья ähnelt.
        /// </summary>
        public static string CommentFilterFriendsOption {
            get {
                return ResourceManager.GetString("CommentFilterFriendsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Укажите свой профиль ähnelt.
        /// </summary>
        public static string CommentsListTemplatesProfileFieldName {
            get {
                return ResourceManager.GetString("CommentsListTemplatesProfileFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Прочитать всю ветку ähnelt.
        /// </summary>
        public static string CommentsListTemplatesReadBranchLinkText {
            get {
                return ResourceManager.GetString("CommentsListTemplatesReadBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ответить ähnelt.
        /// </summary>
        public static string CommentsListTemplatesReplyHeading {
            get {
                return ResourceManager.GetString("CommentsListTemplatesReplyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ответить ähnelt.
        /// </summary>
        public static string CommentsListTemplatesReplyLinkText {
            get {
                return ResourceManager.GetString("CommentsListTemplatesReplyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string CommentsListTemplatesSaveButtonText {
            get {
                return ResourceManager.GetString("CommentsListTemplatesSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сказать! ähnelt.
        /// </summary>
        public static string CommentsListTemplatesSayButtonText {
            get {
                return ResourceManager.GetString("CommentsListTemplatesSayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Управление ähnelt.
        /// </summary>
        public static string LayoutHeaderAdminLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderAdminLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Книги ähnelt.
        /// </summary>
        public static string LayoutHeaderBooksLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderBooksLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Главная ähnelt.
        /// </summary>
        public static string LayoutHeaderHomeLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderHomeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Уведомления ähnelt.
        /// </summary>
        public static string LayoutHeaderNotificationsLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderNotificationsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читатели ähnelt.
        /// </summary>
        public static string LayoutHeaderReadersLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderReadersLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die регистрация ähnelt.
        /// </summary>
        public static string LayoutHeaderRegisterLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderRegisterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die войти ähnelt.
        /// </summary>
        public static string LayoutHeaderSigninLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderSigninLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die выйти ähnelt.
        /// </summary>
        public static string LayoutHeaderSignOutLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderSignOutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Авторам ähnelt.
        /// </summary>
        public static string LayoutHeaderToAuthorsLinkText {
            get {
                return ResourceManager.GetString("LayoutHeaderToAuthorsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die введите пароль ähnelt.
        /// </summary>
        public static string LoginBoxEnterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginBoxEnterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль ähnelt.
        /// </summary>
        public static string LoginBoxPasswordFieldName {
            get {
                return ResourceManager.GetString("LoginBoxPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Войти ähnelt.
        /// </summary>
        public static string LoginBoxSigninButtonText {
            get {
                return ResourceManager.GetString("LoginBoxSigninButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string RegisterBoxNameFieldName {
            get {
                return ResourceManager.GetString("RegisterBoxNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string RegisterBoxNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterBoxNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль ähnelt.
        /// </summary>
        public static string RegisterBoxPasswordFieldName {
            get {
                return ResourceManager.GetString("RegisterBoxPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die придумайте пароль ähnelt.
        /// </summary>
        public static string RegisterBoxPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterBoxPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Зарегистрироваться ähnelt.
        /// </summary>
        public static string RegisterBoxRegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterBoxRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxNameFieldName {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die или ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxOrMessage {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxOrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxPasswordFieldName {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die придумайте пароль ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Зарегистрироваться ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxRegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Войти ähnelt.
        /// </summary>
        public static string RegisterOrLoginBoxSignInLinkText {
            get {
                return ResourceManager.GetString("RegisterOrLoginBoxSignInLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пожалуйста, укажите свой профиль в социальной сети ähnelt.
        /// </summary>
        public static string SocialLoginBoxHeading {
            get {
                return ResourceManager.GetString("SocialLoginBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die или ähnelt.
        /// </summary>
        public static string SocialLoginBoxOrMessage {
            get {
                return ResourceManager.GetString("SocialLoginBoxOrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль ähnelt.
        /// </summary>
        public static string SocialLoginBoxPasswordFieldName {
            get {
                return ResourceManager.GetString("SocialLoginBoxPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die введите пароль ähnelt.
        /// </summary>
        public static string SocialLoginBoxPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SocialLoginBoxPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string SocialLoginBoxSaveButtonText {
            get {
                return ResourceManager.GetString("SocialLoginBoxSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Войдите ähnelt.
        /// </summary>
        public static string SocialLoginBoxSignInLinkText {
            get {
                return ResourceManager.GetString("SocialLoginBoxSignInLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Когда отвечают на мой комментарий ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsBoxNotifyReplyFieldName {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsBoxNotifyReplyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsBoxSaveButtonText {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsBoxSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Настройка уведомлений ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsViewHeading {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsViewHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Когда отвечают на мой комментарий ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsViewNotifyReplyFieldName {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsViewNotifyReplyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сохранить ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsViewSaveButtonText {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsViewSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Настройка уведомлений ähnelt.
        /// </summary>
        public static string UpdateNotificationSettingsViewTitle {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingsViewTitle", resourceCulture);
            }
        }
    }
}
