//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SideNotes.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SideNotes.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die к этой книге ähnelt.
        /// </summary>
        public static string BestCommentCountMessage {
            get {
                return ResourceManager.GetString("BestCommentCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Подтвердите пароль ähnelt.
        /// </summary>
        public static string ChangePasswordBoxConfirmPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordBoxConfirmPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Текущий пароль ähnelt.
        /// </summary>
        public static string ChangePasswordBoxCurrentPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordBoxCurrentPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Новый пароль ähnelt.
        /// </summary>
        public static string ChangePasswordBoxNewPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordBoxNewPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string ChangePasswordBoxSubmitButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordBoxSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Изменить пароль ähnelt.
        /// </summary>
        public static string ChangePasswordViewChangePasswordHeading {
            get {
                return ResourceManager.GetString("ChangePasswordViewChangePasswordHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Изменить пароль ähnelt.
        /// </summary>
        public static string ChangePasswordViewChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordViewChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Подтвердите пароль ähnelt.
        /// </summary>
        public static string ChangePasswordViewConfirmPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordViewConfirmPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Текущий пароль ähnelt.
        /// </summary>
        public static string ChangePasswordViewCurrentPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordViewCurrentPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Новый пароль ähnelt.
        /// </summary>
        public static string ChangePasswordViewNewPasswordFieldName {
            get {
                return ResourceManager.GetString("ChangePasswordViewNewPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string ChangePasswordViewSubmitButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordViewSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (скрытый) ähnelt.
        /// </summary>
        public static string CommentsPageHiddenMessage {
            get {
                return ResourceManager.GetString("CommentsPageHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Еще от этого пользователя ähnelt.
        /// </summary>
        public static string CommentsPageMoreFromThisUserMessage {
            get {
                return ResourceManager.GetString("CommentsPageMoreFromThisUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Прочитать всю ветку ähnelt.
        /// </summary>
        public static string CommentsPageReadBranchLinkText {
            get {
                return ResourceManager.GetString("CommentsPageReadBranchLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читать книгу с этого места ähnelt.
        /// </summary>
        public static string CommentsPageReadFromHereLinkText {
            get {
                return ResourceManager.GetString("CommentsPageReadFromHereLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ответить ähnelt.
        /// </summary>
        public static string CommentsPageReplyLinkText {
            get {
                return ResourceManager.GetString("CommentsPageReplyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ЗАВЕРШИТЬ РЕГИСТРАЦИЮ ähnelt.
        /// </summary>
        public static string CompleteExternalRegistrationCompleteRegistrationLinkText {
            get {
                return ResourceManager.GetString("CompleteExternalRegistrationCompleteRegistrationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Завершение регистрации ähnelt.
        /// </summary>
        public static string CompleteExternalRegistrationTitle {
            get {
                return ResourceManager.GetString("CompleteExternalRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alepush@gmail.com ähnelt.
        /// </summary>
        public static string CompleteRegistrationBoxEmailPlaceholder {
            get {
                return ResourceManager.GetString("CompleteRegistrationBoxEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string CompleteRegistrationBoxNameFieldName {
            get {
                return ResourceManager.GetString("CompleteRegistrationBoxNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string CompleteRegistrationBoxNamePlaceholder {
            get {
                return ResourceManager.GetString("CompleteRegistrationBoxNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string CompleteRegistrationBoxSubmitButtonText {
            get {
                return ResourceManager.GetString("CompleteRegistrationBoxSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нельзя менять пароль на внешнем аккаунте ähnelt.
        /// </summary>
        public static string ControllerCantChangePasswordOnExternalAccount {
            get {
                return ResourceManager.GetString("ControllerCantChangePasswordOnExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Текущий пароль введен не верно ähnelt.
        /// </summary>
        public static string ControllerCurrentPasswordDoesntMatch {
            get {
                return ResourceManager.GetString("ControllerCurrentPasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читатель с таким емейлом уже существует ähnelt.
        /// </summary>
        public static string ControllerEmailIsAlreadyUsed {
            get {
                return ResourceManager.GetString("ControllerEmailIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Неверный формат данных ähnelt.
        /// </summary>
        public static string ControllerInvalidFormat {
            get {
                return ResourceManager.GetString("ControllerInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Нужно залогиниться ähnelt.
        /// </summary>
        public static string ControllerMustLogin {
            get {
                return ResourceManager.GetString("ControllerMustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Недостаточно прав для редактирования профиля этого пользователя ähnelt.
        /// </summary>
        public static string ControllerNoPermissionsToEditUser {
            get {
                return ResourceManager.GetString("ControllerNoPermissionsToEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Повторный ввод не совпадает с первым. Попробуйте ещё раз ähnelt.
        /// </summary>
        public static string ControllerPasswordConfirmationDoesntMatch {
            get {
                return ResourceManager.GetString("ControllerPasswordConfirmationDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пользователь не найден ähnelt.
        /// </summary>
        public static string ControllerUserNotFound {
            get {
                return ResourceManager.GetString("ControllerUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пользователь не был зарегистрирован ähnelt.
        /// </summary>
        public static string ControllerUserNotRegistered {
            get {
                return ResourceManager.GetString("ControllerUserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alepush@gmail.com ähnelt.
        /// </summary>
        public static string EditProfileBoxEmailPlaceholder {
            get {
                return ResourceManager.GetString("EditProfileBoxEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string EditProfileBoxNameFieldName {
            get {
                return ResourceManager.GetString("EditProfileBoxNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string EditProfileBoxNamePlaceholder {
            get {
                return ResourceManager.GetString("EditProfileBoxNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string EditProfileBoxSubmitButtonText {
            get {
                return ResourceManager.GetString("EditProfileBoxSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alepush@gmail.com ähnelt.
        /// </summary>
        public static string EditProfileViewEmailPlaceholder {
            get {
                return ResourceManager.GetString("EditProfileViewEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Изменить профиль ähnelt.
        /// </summary>
        public static string EditProfileViewHeading {
            get {
                return ResourceManager.GetString("EditProfileViewHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string EditProfileViewNameFieldName {
            get {
                return ResourceManager.GetString("EditProfileViewNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string EditProfileViewNamePlaceholder {
            get {
                return ResourceManager.GetString("EditProfileViewNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string EditProfileViewSubmitButtonText {
            get {
                return ResourceManager.GetString("EditProfileViewSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Изменить профиль ähnelt.
        /// </summary>
        public static string EditProfileViewTitle {
            get {
                return ResourceManager.GetString("EditProfileViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читатели ähnelt.
        /// </summary>
        public static string IndexHeading {
            get {
                return ResourceManager.GetString("IndexHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die подписаться ähnelt.
        /// </summary>
        public static string IndexSubscribeButtonText {
            get {
                return ResourceManager.GetString("IndexSubscribeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читатели ähnelt.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die отписаться ähnelt.
        /// </summary>
        public static string IndexUnsubscribeButtonText {
            get {
                return ResourceManager.GetString("IndexUnsubscribeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить профиль ähnelt.
        /// </summary>
        public static string MySocialProfilesAddProfileLinkText {
            get {
                return ResourceManager.GetString("MySocialProfilesAddProfileLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ещё ähnelt.
        /// </summary>
        public static string RecentCommentsMoreMessage {
            get {
                return ResourceManager.GetString("RecentCommentsMoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die alepush@gmail.com ähnelt.
        /// </summary>
        public static string RegisterEmailPlaceholder {
            get {
                return ResourceManager.GetString("RegisterEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Регистрация ähnelt.
        /// </summary>
        public static string RegisterHeading {
            get {
                return ResourceManager.GetString("RegisterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отображаемое имя ähnelt.
        /// </summary>
        public static string RegisterNameFieldName {
            get {
                return ResourceManager.GetString("RegisterNameFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Александр Пушкин ähnelt.
        /// </summary>
        public static string RegisterNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Пароль ähnelt.
        /// </summary>
        public static string RegisterPasswordFieldName {
            get {
                return ResourceManager.GetString("RegisterPasswordFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die придумайте пароль ähnelt.
        /// </summary>
        public static string RegisterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Отправить ähnelt.
        /// </summary>
        public static string RegisterSubmitButtonText {
            get {
                return ResourceManager.GetString("RegisterSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Регистрация ähnelt.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Выберите аватар ähnelt.
        /// </summary>
        public static string SetAvatarBoxHeading {
            get {
                return ResourceManager.GetString("SetAvatarBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Загрузить ähnelt.
        /// </summary>
        public static string SetAvatarBoxUploadButtonText {
            get {
                return ResourceManager.GetString("SetAvatarBoxUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Новый аватар ähnelt.
        /// </summary>
        public static string SetAvatarHeading {
            get {
                return ResourceManager.GetString("SetAvatarHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Новый аватар ähnelt.
        /// </summary>
        public static string SetAvatarTitle {
            get {
                return ResourceManager.GetString("SetAvatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Загрузить ähnelt.
        /// </summary>
        public static string SetAvatarUploadButtonText {
            get {
                return ResourceManager.GetString("SetAvatarUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить профиль ähnelt.
        /// </summary>
        public static string ViewAddProfileLinkText {
            get {
                return ResourceManager.GetString("ViewAddProfileLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cобеседники ähnelt.
        /// </summary>
        public static string ViewAddUserHeading {
            get {
                return ResourceManager.GetString("ViewAddUserHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Добавить ähnelt.
        /// </summary>
        public static string ViewAddUserLinkText {
            get {
                return ResourceManager.GetString("ViewAddUserLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Лучший комментарий ähnelt.
        /// </summary>
        public static string ViewBestCommentHeading {
            get {
                return ResourceManager.GetString("ViewBestCommentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Изменить пароль ähnelt.
        /// </summary>
        public static string ViewChangePasswordLinkText {
            get {
                return ResourceManager.GetString("ViewChangePasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Контакты ähnelt.
        /// </summary>
        public static string ViewContactsMessage {
            get {
                return ResourceManager.GetString("ViewContactsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ред. ähnelt.
        /// </summary>
        public static string ViewEditLinkText {
            get {
                return ResourceManager.GetString("ViewEditLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Уведомления ähnelt.
        /// </summary>
        public static string ViewNotificationsLinkText {
            get {
                return ResourceManager.GetString("ViewNotificationsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сейчас читает ähnelt.
        /// </summary>
        public static string ViewReadsNowHeading {
            get {
                return ResourceManager.GetString("ViewReadsNowHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cвежие комментарии к прочитанному ähnelt.
        /// </summary>
        public static string ViewRecentCommentsHeading {
            get {
                return ResourceManager.GetString("ViewRecentCommentsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Настройки ähnelt.
        /// </summary>
        public static string ViewSettingsMessage {
            get {
                return ResourceManager.GetString("ViewSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Логин ähnelt.
        /// </summary>
        public static string ViewSigninLinkText {
            get {
                return ResourceManager.GetString("ViewSigninLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die подписаться ähnelt.
        /// </summary>
        public static string ViewSubscribeButtonText {
            get {
                return ResourceManager.GetString("ViewSubscribeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Читатель ähnelt.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die отписаться ähnelt.
        /// </summary>
        public static string ViewUnsubscribeButtonText {
            get {
                return ResourceManager.GetString("ViewUnsubscribeButtonText", resourceCulture);
            }
        }
    }
}
